DMC_T001_CONSTRAINED = load("DMC_T001_CONSTRAINED.txt");
DMC_T001_CONSTRAINED_CONTROL = load("DMC_T001_CONSTRAINED_CONTROL.txt");

DMC_T001_NOTCONSTRAINED = load("DMC_T001_NOTCONSTRAINED.txt");
DMC_T001_NOTCONSTRAINED_CONTROL = load("DMC_T001_NOTCONSTRAINED_CONTROL.txt");

DMC_T01_CONSTRAINED = load("DMC_T01_CONSTRAINED.txt");
DMC_T01_CONSTRAINED_CONTROL = load("DMC_T01_CONSTRAINED_CONTROL.txt");

DMC_T01_NOTCONSTRAINED = load("DMC_T01_NOTCONSTRAINED.txt");
DMC_T01_NOTCONSTRAINED_CONTROL = load("DMC_T01_NOTCONSTRAINED_CONTROL.txt");

DMC_T1_CONSTRAINED = load("DMC_T1_CONSTRAINED.txt");
DMC_T1_CONSTRAINED_CONTROL = load("DMC_T1_CONSTRAINED_CONTROL.txt");

DMC_T1_NOTCONSTRAINED = load("DMC_T1_NOTCONSTRAINED.txt");
DMC_T1_NOTCONSTRAINED_CONTROL = load("DMC_T1_NOTCONSTRAINED_CONTROL.txt");

Samples = 0:1:500;
time = 0.01 * Samples;

plot(time, DMC_T001_CONSTRAINED)
hold;
plot(time, DMC_T01_CONSTRAINED)
plot(time, DMC_T1_CONSTRAINED)
grid on;
hold;

figure;
plot(time, DMC_T001_NOTCONSTRAINED)
hold;
plot(time, DMC_T01_NOTCONSTRAINED)
plot(time, DMC_T1_NOTCONSTRAINED)
grid on;
hold;


